Modul 2 Class 5 Assignment

In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url) #it opens the file
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce').fillna(0)  #it is turning text into number, missing values in to NaN, Then it is turning this NaN values into 0   #uploading python libraries to work with
print('Shape:', df.shape) #it shows how many rows and columns we have

Shape: (7043, 21)

In [4]:
df.info() #it shows what kind of datatype each column has

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [5]:
df.describe().round(2) # Calculate key summary statistics for numerical columns and round the results to 2 decimal places

       SeniorCitizen   tenure  MonthlyCharges  TotalCharges
count        7043.00  7043.00         7043.00       7043.00
mean            0.16    32.37           64.76       2279.73
std             0.37    24.56           30.09       2266.79
min             0.00     0.00           18.25          0.00
25%             0.00     9.00           35.50        398.55
50%             0.00    29.00           70.35       1394.55
75%             0.00    55.00           89.85       3786.60
max             1.00    72.00          118.75       8684.80

In [6]:
df.nunique() #it showshow many different values each column has

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [7]:
high_pay = df[df['MonthlyCharges'] > 80]  #it is creating the column called high_pay which only includes the values above 80 from monthly charges column
print('High-paying customers:', len(high_pay)) #it count how many these high pay custumers there are
high_pay.head() #it shows the first 5 rows

High-paying customers: 2666

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
12,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.10,No
13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes

In [8]:
top10 = df.sort_values('tenure', ascending=False).head(10) #it shows 10 tenure values from highest to the lowest
top10[['customerID', 'tenure', 'Contract', 'MonthlyCharges']] # Create a cleaner view of the 'top10' table by selecting and displaying only these 4 specific columns

      customerID  tenure  Contract  MonthlyCharges
3177  1814-WFGVS      72  Two year           48.90
3131  8336-TAVKX      72  Two year           78.45
3107  5038-ETMLM      72  Two year          113.65
35    6234-RAAPL      72  Two year           99.90
3111  8809-RIHDD      72  Two year          103.40
3112  8809-XKHMD      72  Two year          100.55
3203  5879-HMFFH      72  Two year           88.05
3205  3810-DVDQQ      72  Two year          117.60
3247  8853-TZDGH      72  Two year          111.60
3266  0464-WJTKO      72  Two year           20.10

In [9]:
df.groupby('PaymentMethod')['MonthlyCharges'].mean().round(2)  #it calculates the average value of monthly charges for each payment method

PaymentMethod
Bank transfer (automatic)    67.19
Credit card (automatic)      66.51
Electronic check             76.26
Mailed check                 43.92
Name: MonthlyCharges, dtype: float64

In [11]:
df.groupby('Churn').agg({'TotalCharges': ['mean', 'count']}).round(2) #it calculates the average value of total charges for churn, rounded to 2 decimal numbers

      TotalCharges
              mean count
Churn
No         2549.91  5174
Yes        1531.80  1869

In [12]:
pd.crosstab(df['Contract'], df['Churn']) #Cross-tabulation to count the number of stayed (No) and churned (Yes) customers for each contract type

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48